# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath E:/shuziluoji/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/zjd/police/police.cache/wt [current_project]
set_property parent.project_path C:/Users/zjd/police/police.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files f:/360MoveData/Users/zjd/Desktop/s11.coe
add_files f:/360MoveData/Users/zjd/Desktop/s22.coe
add_files -quiet c:/Users/zjd/police/police.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp
set_property used_in_implementation false [get_files c:/Users/zjd/police/police.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp]
add_files -quiet c:/Users/zjd/police/police.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files c:/Users/zjd/police/police.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/zjd/police/police.srcs/sources_1/new/speaker.v
  C:/Users/zjd/police/police.srcs/sources_1/new/title.v
  C:/Users/zjd/police/police.srcs/sources_1/new/time_text.v
  C:/Users/zjd/police/police.srcs/sources_1/new/siren2.v
  C:/Users/zjd/police/police.srcs/sources_1/new/siren1.v
  C:/Users/zjd/police/police.srcs/sources_1/new/score.v
  C:/Users/zjd/police/police.srcs/sources_1/new/paratitle.v
  C:/Users/zjd/police/police.srcs/sources_1/new/font_rom.v
  C:/Users/zjd/police/police.srcs/sources_1/new/start_text.v
  C:/Users/zjd/police/police.srcs/sources_1/new/game_over.v
  C:/Users/zjd/police/police.srcs/sources_1/new/ps2_transmitter.v
  C:/Users/zjd/police/police.srcs/sources_1/new/Devider.v
  C:/Users/zjd/police/police.srcs/sources_1/new/text.v
  C:/Users/zjd/police/police.srcs/sources_1/new/cursor.v
  C:/Users/zjd/police/police.srcs/sources_1/new/road.v
  C:/Users/zjd/police/police.srcs/sources_1/new/yellowline.v
  C:/Users/zjd/police/police.srcs/sources_1/new/people.v
  C:/Users/zjd/police/police.srcs/sources_1/new/car.v
  C:/Users/zjd/police/police.srcs/sources_1/new/mouse.v
  C:/Users/zjd/police/police.srcs/sources_1/new/siren.v
  C:/Users/zjd/police/police.srcs/sources_1/new/sound.v
  C:/Users/zjd/police/police.srcs/sources_1/new/vga_display.v
  C:/Users/zjd/police/police.srcs/sources_1/new/game_state.v
  C:/Users/zjd/police/police.srcs/sources_1/new/vga_sync.v
  C:/Users/zjd/police/police.srcs/sources_1/new/police_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/zjd/police/police.srcs/constrs_1/new/police_xdc.xdc
set_property used_in_implementation false [get_files C:/Users/zjd/police/police.srcs/constrs_1/new/police_xdc.xdc]


synth_design -top police_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef police_top.dcp

catch { report_utilization -file police_top_utilization_synth.rpt -pb police_top_utilization_synth.pb }
